import axios from 'axios';

export const GET_SMURF = "GET_SMURF";
// export const POST_SMURF = "POST_SMURF";
export const SHOWING_SMURF = "SHOWING_SMURF";
export const ERROR_SMURF = "ERROR_SMURF";

// DONT FORGET TO PACK-A-PUNCH YOUR ACTIONS!!!!!

export const getSmurf = () => dispatch => {
    dispatch({ type: GET_SMURF});
    setTimeout(() => {
        axios
            .get('http://localhost:3333/smurfs')
            .then(res => {
                console.log('YES HELLO THESE ARE THE SMURF U ASKED: ', res);
                dispatch({ type: SHOWING_SMURF, smurfs: res});
            })
            .catch(err => {
                console.log('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH ', err);
                dispatch({type: ERROR_SMURF, error: "We've run into a problem getting the smurfs... Your name doesn't happen to be Gargamel, does it?"})
            });
    }, 1000);
};

// export const postSmurf = () => dispatch => {
//     console.log('POSTING SMURF TRIGGERED');
//     dispatch({ type: POST_SMURF});
//     axios
//         .get('http://localhost:3333/smurfs', dispatch)
//         .then(res => {
//             console.log('SMURFS THAT HAVE BEEN SENT::::::::::: ', res);
//         })
//         .catch(err => {
//             console.log('AAAAAHHHHHHHH ', err);
//             dispatch({type: ERROR_SMURF, error: "We've run into a problem getting the smurfs... Your name doesn't happen to be Gargamel, does it?"})
//         });
// };
